apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sudo-service-requester
rules:
  - apiGroups: ["sudo.andrewgarrett.dev"]
    resources: ["sudorequests"]
    verbs: ["create", "get", "list", "watch"]
