apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sudo-service-requesters
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sudo-service-requester
subjects:
{{- range .Values.requesters }}
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ .namespace }}
{{- end }}
