{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sudo-service
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_role]
          regex: executor
          action: drop
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: sudo-service
{{- end }}
