apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: sudo-service-requester-validation
spec:
  policyName: sudo-service-requester-validation
  validationActions:
    - Deny
